## WiSHFUL Agent config file

agent_info:
  name: 'agent1'
  info: 'agent_info'
  iface: 'lo'

modules:
  discovery:
      module : wishful_module_discovery_pyre
      class_name : PyreDiscoveryAgentModule
      kwargs: {"iface":"lo", "groupName":"wishful_coral"}

  rule_manager:
      module : wishful_module_rules
      class_name : RuleManagerModule

  simple:
      module : wishful_module_simple
      class_name : SimpleModule2
      interfaces : ['wlan0', 'wlan1']

  iperf:
      module : wishful_module_iperf
      class_name : IperfModule
  gitar_engine:
      module : wishful_module_gitar
      class_name : GitarEngine
      interfaces : ['lowpan0']
      kwargs : {'GitarConfig' : './gitar1.ini','SupportedInterfaces' : ['lowpan0'],'ControlExtensions' : {'taisc' : './taisc_control_extensions1.csv', 'rime' : './rime_control_extensions.csv'}}
  taisc_connector:
      module : wishful_module_taisc
      class_name : TAISCConnector
      interfaces : ['lowpan0']
      kwargs : {'RadioPrograms' : {"CSMA":0,"TDMA":2,"TSCH":1}, 'SupportedInterfaces' : ['lowpan0']}
  rime_connector:
      module : wishful_module_rime
      class_name : RIMEConnector
      interfaces : ['lowpan0']
      kwargs : {'SupportedInterfaces' : ['lowpan0']}
